version: '3.8'

services:
  diskwala-bot:
    build: .
    container_name: diskwala-downloader-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./bot.log:/app/bot.log
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
